# Generated by Django 3.2.13 on 2022-06-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_user_image',
        ),
    ]
