# Generated by Django 3.2.13 on 2022-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profile_picture',
            new_name='author_picture',
        ),
    ]
