# Generated by Django 3.2.13 on 2022-05-31 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220531_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
