# Generated by Django 3.2.13 on 2022-06-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_author_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.profile'),
        ),
    ]
