# Generated by Django 3.2.13 on 2022-06-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_image',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='posts.profile'),
        ),
    ]
