# Generated by Django 3.2.13 on 2022-06-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
    ]
