# Generated by Django 3.2.13 on 2022-06-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='posts.profile'),
        ),
    ]
