# Generated by Django 3.2.13 on 2022-06-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220605_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_profile_image',
        ),
    ]
