# Generated by Django 3.2.13 on 2022-06-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_comment_comment_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_profile_image',
        ),
    ]
