# Generated by Django 3.2.13 on 2022-06-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_comment_comment_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comment_profile_image',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='posts.profile'),
        ),
    ]
