# Generated by Django 3.2.13 on 2022-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_comment_comment_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
